### ISSUE TITLE
  When I run the code, I get this error

### ISSUE THREAD

**Issue by why19950611** [ericbenhamou/cHMM#1]
Traceback (most recent call last):
  File "/home/why/PycharmProjects/HMM-CHMM/stock-predict-master/CHmm/main.py", line 69, in <module>
    hs_data = transform_data(df.HS, obs_states)
  File "/home/why/PycharmProjects/HMM-CHMM/stock-predict-master/CHmm/main.py", line 19, in transform_data
    index = np.where(obs_range > rsi.values[i])[0][0] - 1
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by why19950611** [comment]
How can I solve it
